select
    kpi_code,
    kpi_layer,
    kpi_name,
    dbt_coverage_status,
    dbt_model_name,
    coverage_note
from (
    values
        ('A1', 'A', 'API Availability', 'not_dbt', null, 'Requires API request metrics from Prometheus/APM.'),
        ('A2', 'A', 'API Latency P95', 'not_dbt', null, 'Requires latency histogram from Prometheus/APM.'),
        ('A3', 'A', 'Scheduler Success Rate', 'covered', 'fct_scheduler_health_daily', 'Covered from scheduler_log status counts.'),
        ('A4', 'A', 'Queue Backlog Health', 'not_dbt', null, 'Requires queue depth metrics.'),
        ('A5', 'A', 'Incident MTTR', 'external_source_required', null, 'Requires incident tracker/event store.'),
        ('A6', 'A', 'Throughput Headroom', 'external_source_required', null, 'Requires benchmark/load test export.'),
        ('A7', 'A', 'Saturation Compliance', 'not_dbt', null, 'Requires infra metrics from Prometheus/APM.'),
        ('B1', 'B', 'Query Validity Rate', 'external_source_required', null, 'Requires first-run validity/evaluation cases.'),
        ('B2', 'B', 'Dashboard/Chart Reuse Rate', 'covered', 'fct_bi_artifact_reuse_30d', 'Covered from chart/dashboard view analytics.'),
        ('B3', 'B', 'Visualization Fidelity Rate', 'external_source_required', null, 'Requires expected artifact evaluation cases.'),
        ('B4', 'B', 'Business KPI Governance Coverage', 'external_source_required', null, 'Requires business KPI semantic governance inventory.'),
        ('C1', 'C', 'TTFT P95', 'not_dbt', null, 'Requires stream first-token telemetry.'),
        ('C2', 'C', 'End-to-End Response P95', 'covered', 'fct_ai_thread_response_times', 'Covered from ai_prompt responded_at - created_at.'),
        ('C3', 'C', 'Tool Success Rate', 'partially_covered', 'fct_ai_tool_success_daily', 'Uses tool result presence as success proxy.'),
        ('C4', 'C', 'Hallucination Proxy Rate', 'covered', 'fct_ai_feedback_daily', 'Uses downvote feedback as hallucination proxy.'),
        ('C5', 'C', 'Step-Cap Reached Rate', 'not_dbt', null, 'Requires AI service step-cap counter or session trace field.'),
        ('C6', 'C', 'Concurrent Session Stability', 'external_source_required', null, 'Requires benchmark run results.'),
        ('C7', 'C', 'AI Request Availability', 'external_source_required', null, 'Requires synthetic request or LLM availability checks.'),
        ('C8', 'C', 'Policy Denial Correctness', 'external_source_required', null, 'Requires negative policy test results.'),
        ('D1', 'D', 'Unauthorized Data Exposure', 'external_source_required', null, 'Requires security incident/event store.'),
        ('D2', 'D', 'Audit Trace Coverage', 'partially_covered', 'fct_ai_thread_response_times', 'Can verify persisted prompt/thread coverage, not full distributed trace completeness.'),
        ('D3', 'D', 'Sensitive Log Leakage', 'external_source_required', null, 'Requires log scanning results.'),
        ('D4', 'D', 'Policy Compliance Score', 'external_source_required', null, 'Requires policy test results.'),
        ('D5', 'D', 'Access Control Test Pass Rate', 'external_source_required', null, 'Requires access-control test results.'),
        ('E1', 'E', 'Cost per Successful Session', 'partially_covered', 'fct_ai_thread_characters', 'Character metrics available; requires cost.Tele for full cost calculation.'),
        ('E2', 'E', 'Token Efficiency', 'partially_covered', 'fct_ai_thread_characters', 'Character metrics available as token proxy; requires actual token counts for precise efficiency.'),
        ('E3', 'E', 'Escalation Rate', 'external_source_required', null, 'Requires escalation handoff records.'),
        ('E4', 'E', 'On-call Noise Ratio', 'external_source_required', null, 'Requires alert/incident management data.'),
        ('M1', 'F', 'Metadata Completeness Score', 'external_source_required', null, 'Requires semantic metadata inventory with owner/tag/glossary/lineage.'),
        ('Q1', 'F', 'Critical Dataset Quality Score', 'external_source_required', null, 'Requires data quality test results.'),
        ('U1', 'G', 'DAU', 'covered', 'fct_ai_adoption_daily', 'Covered from BI view analytics and AI prompt activity.'),
        ('U2', 'G', 'MAU', 'covered', 'fct_ai_adoption_daily', 'Can be calculated by month from daily activity.'),
        ('U3', 'G', 'Business Self-Service Rate', 'external_source_required', null, 'Requires success/no-escalation labels.'),
        ('U4', 'G', 'AI Usage Rate', 'covered', 'fct_ai_adoption_daily', 'Covered as AI active users over BI active users.'),
        ('U5', 'G', 'Dashboard Adoption Rate', 'covered', 'fct_dashboard_usage_daily', 'Covered from dashboard view analytics over selected window.')
) as t(kpi_code, kpi_layer, kpi_name, dbt_coverage_status, dbt_model_name, coverage_note)
