# docker network create authelia-proxy-external
volumes:
  prefect_data:
  prefect_postgres:

networks:
  authelia-proxy-external:
    external: true
    # driver: bridge

services:
  prefect-nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "9443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - prefect-authelia
      - prefect-server
    restart: unless-stopped
    networks:
      - authelia-proxy-external
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  prefect-authelia:
    image: authelia/authelia:4.38
    container_name: authelia
    volumes:
      - ./authelia:/config
    restart: unless-stopped
    networks:
      - authelia-proxy-external
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  # prefect-postgres:
  #   security_opt:
  #     - seccomp=unconfined
  #   image: postgres:13
  #   container_name: prefect-postgres
  #   environment:
  #     POSTGRES_USER: prefect
  #     POSTGRES_PASSWORD: prefect
  #     POSTGRES_DB: prefect
  #   volumes:
  #     - prefect_postgres:/var/lib/postgresql/data
  #   networks:
  #     - authelia-proxy-external

  # ---------------- PREFECT SERVER ----------------
  prefect-server:
    security_opt:
      - seccomp=unconfined
    image: prefecthq/prefect:3-python3.11
    container_name: prefect-server
    command: prefect server start --host 0.0.0.0
    # ports: ["127.0.0.1:4200:4200"]
    volumes:
      - prefect_data:/root/.prefect
    environment:
      # - PREFECT_API_DATABASE_CONNECTION_URL1=postgresql+asyncpg://prefect:prefect@prefect-postgres:5432/prefect
      - PREFECT_API_DATABASE_CONNECTION_URL=sqlite+aiosqlite:////root/.prefect/prefect.db
      - PREFECT_UI_URL=https://prefect-external.viettelcyber.com
      - PREFECT_API_URL=https://prefect-external.viettelcyber.com/api
      - PREFECT_SERVER_ANALYTICS_ENABLED=false
    extra_hosts:
      - "prefect-external.viettelcyber.com:10.254.130.46"
    networks:
      - authelia-proxy-external
    depends_on:
      - prefect-authelia
      # - prefect-postgres
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
