events {}

http {
  upstream authelia {
    server authelia:9091;
  }

  upstream prefect {
    server prefect-server:4200;
  }

  ## ========= AUTH PREFECT =========
  server {
    listen 443 ssl;
    server_name prefect-external.viettelcyber.com;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    # location /api/ {
    #     # set_real_ip_from 192.168.1.0/24;
    #     # real_ip_header X-Forwarded-For;
    #     # real_ip_recursive on;

    #     # --------- IP WHITELIST ---------
    #     allow 10.255.245.150;
    #     allow 192.168.59.206;
    #     allow 192.168.6.158;
    #     deny all;

    #     # --------- PROXY ---------
    #     proxy_pass http://prefect/api/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Forwarded-Proto https;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     # add_header X-Debug-IP $remote_addr always;
    #     auth_request off;
    # }

    ## Forward auth
    location / {
      auth_request /authelia;
      error_page 401 =302 https://auth.prefect-external.viettelcyber.com?rd=$scheme://$host$request_uri;

      proxy_pass http://prefect;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header X-Forwarded-Proto https;
    }

    

    location = /authelia {
      internal;
      proxy_pass http://authelia/api/verify;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Uri $request_uri;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header Content-Length "";
      proxy_pass_request_body off;
    }
  }

  ## ========= AUTHELIA LOGIN =========
  server {
    listen 443 ssl;
    server_name auth.prefect-external.viettelcyber.com;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    location / {
      proxy_pass http://authelia;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $remote_addr;
    }
  }

  server {
      listen 80;
      server_name auth.prefect-external.viettelcyber.com prefect-external.viettelcyber.com;
      return 301 https://$host$request_uri; # Redirect HTTP sang HTTPS
  }
}

