GRANT ALL PRIVILEGES ON DATABASE n8n TO n8n;
GRANT CONNECT ON DATABASE analytics TO readonly;
-- GRANT ALL PRIVILEGES ON DATABASE metastore TO admin;
GRANT ALL PRIVILEGES ON DATABASE prefect TO prefect;