version: 2
models:
- name: production_management_1_worklogs_projects
  description: "Bảng production_management_1_worklogs_projects (nguồn Power BI: Worklogs_Projects)."
  meta:
    label: "Worklogs_Projects"
    powerbi_source: "Worklogs_Projects"
  columns:
  - name: id
    description: "Cột Id trong Worklogs_Projects."
    meta:
      dimension:
        type: number
        label: "Id"
        hidden: true
  - name: project_name
    description: "Cột PROJECT_NAME trong Worklogs_Projects."
    meta:
      dimension:
        type: string
        label: "PROJECT_NAME"
        hidden: true
  - name: project_key
    description: "Cột PROJECT_KEY trong Worklogs_Projects."
    meta:
      dimension:
        type: string
        label: "PROJECT_KEY"
        hidden: true
