version: 2
models:
- name: production_management_1_milestone_versions_projects
  description: "Bảng production_management_1_milestone_versions_projects (nguồn Power BI: milestone Versions_Projects)."
  meta:
    label: "milestone Versions_Projects"
    powerbi_source: "milestone Versions_Projects"
  columns:
  - name: id
    description: "Cột Id trong milestone Versions_Projects."
    meta:
      dimension:
        type: number
        label: "Id"
        hidden: true
  - name: project_name
    description: "Cột PROJECT_NAME trong milestone Versions_Projects."
    meta:
      dimension:
        type: string
        label: "PROJECT_NAME"
        hidden: true
  - name: project_key
    description: "Cột PROJECT_KEY trong milestone Versions_Projects."
    meta:
      dimension:
        type: string
        label: "PROJECT_KEY"
        hidden: true
  - name: division
    description: "Cột Khối trong milestone Versions_Projects. Cột tính toán, DAX gốc: LOOKUPVALUE('Project vs. Department'[Khối],'Project vs. Department'[ProjectName],'milestone Versions_Projects'[PROJECT_NAME])"
    meta:
      dimension:
        type: string
        label: "Khối"
        hidden: true
