version: 2
sources:
- name: pbi_silver__production_management_1
  database: hive
  schema: "{{ env_var('DBT_TRINO_SCHEMA', 'pbi_silver') }}"
  description: "Silver layer sources for domain: production_management_1"
  tables:
  - name: production_management_1_target_kpikqi_tap_doan
    description: "Nguồn Power BI: Target KPIKQI Tập đoàn"
    columns:
    - name: stt
      description: "Cột STT"
    - name: customer_group
      description: "Cột Nhóm Khách hàng"
    - name: metric_name
      description: "Cột Metric name"
    - name: target_td
      description: "Cột Target_TĐ"
    - name: unit_of_measure_td
      description: "Cột Đơn vị tính_TĐ"
    - name: condition_td
      description: "Cột Điều kiện_TĐ"
    - name: kpi_type_td
      description: "Cột Loại KPI_TĐ"
    - name: note
      description: "Cột Note"
    - name: product_service_name
      description: "Cột Tên SPDV"
    - name: tag
      description: "Cột Tag"
    - name: sp_metric
      description: "Cột SP-Metric"
    - name: column11
      description: "Cột Column11"
