version: 2
sources:
- name: pbi_silver__production_management_1
  database: hive
  schema: "{{ env_var('DBT_TRINO_SCHEMA', 'pbi_silver') }}"
  description: "Silver layer sources for domain: production_management_1"
  tables:
  - name: production_management_1_kpikqi_service_2
    description: "Nguồn Power BI: KPIKQI dịch vụ2"
    columns:
    - name: id
      description: "Cột Id"
    - name: issue_key
      description: "Cột ISSUE_KEY"
    - name: spdv
      description: "Cột SPDV"
    - name: metric_name
      description: "Cột Metric name"
    - name: criteria_period_type
      description: "Cột CriteriaPeriodType"
    - name: result
      description: "Cột Kết quả"
    - name: report_date
      description: "Cột Ngày_báo_cáo_18900"
    - name: target
      description: "Cột Target"
    - name: unit
      description: "Cột Đơn vị"
    - name: condition
      description: "Cột Điều kiện"
    - name: kpi_type
      description: "Cột Loại KPI"
    - name: viettel
      description: "Cột Viettel"
    - name: socp
      description: "Cột SOCP"
    - name: external_customer
      description: "Cột KH ngoài"
    - name: customer_name
      description: "Cột CustomerName"
    - name: customer_type
      description: "Cột CustomerType"
    - name: column12
      description: "Cột Column12"
