version: 2
models:
- name: production_management_1_os_purchase_order
  description: "Bảng production_management_1_os_purchase_order (nguồn Power BI: OS- Đơn đặt hàng)."
  meta:
    label: "OS- Đơn đặt hàng"
    powerbi_source: "OS- Đơn đặt hàng"
    joins:
    - join: production_management_1_os_logwork
      sql_on: "${production_management_1_os_purchase_order.issue_key} = ${production_management_1_os_logwork.issue_key}"
      relationship: one-to-one
  columns:
  - name: id
    description: "Cột Id trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: number
        label: "Id"
        hidden: true
  - name: issue_created
    description: "Cột ISSUE_CREATED trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: timestamp
        label: "ISSUE_CREATED"
        hidden: true
  - name: issue_key
    description: "Cột ISSUE_KEY trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: string
        label: "ISSUE_KEY"
        hidden: true
  - name: issue_summary
    description: "Cột ISSUE_SUMMARY trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: string
        label: "ISSUE_SUMMARY"
        hidden: true
  - name: issue_priority
    description: "Cột ISSUE_PRIORITY trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: string
        label: "ISSUE_PRIORITY"
        hidden: true
  - name: issue_project_id
    description: "Cột ISSUE_PROJECT_ID trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: number
        label: "ISSUE_PROJECT_ID"
        hidden: true
  - name: order_value
    description: "Cột Đơn_hàng_13421 trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: string
        label: "Đơn_hàng_13421"
        hidden: true
  - name: issue_current_status_name
    description: "Cột ISSUE_CURRENT_STATUS_NAME trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: string
        label: "ISSUE_CURRENT_STATUS_NAME"
        hidden: true
  - name: ttsx_product
    description: "Cột TTSX_PRODUCT_16800 trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: string
        label: "TTSX_PRODUCT_16800"
        hidden: true
  - name: severity
    description: "Cột Severity_11301 trong OS- Đơn đặt hàng."
    meta:
      dimension:
        type: string
        label: "Severity_11301"
        hidden: true
