version: 2
sources:
- name: pbi_silver__production_management_1
  database: hive
  schema: "{{ env_var('DBT_TRINO_SCHEMA', 'pbi_silver') }}"
  description: "Silver layer sources for domain: production_management_1"
  tables:
  - name: production_management_1_cycle_time_projects
    description: "Nguồn Power BI: Cycle Time_Projects"
    columns:
    - name: id
      description: "Cột Id"
    - name: project_name
      description: "Cột PROJECT_NAME"
