version: 2
models:
- name: production_management_1_post_acceptance_bug_projects
  description: "Bảng production_management_1_post_acceptance_bug_projects (nguồn Power BI: Bug sau nghiệm thu- Projects)."
  meta:
    label: "Bug sau nghiệm thu- Projects"
    powerbi_source: "Bug sau nghiệm thu- Projects"
    joins:
    - join: production_management_1_milestone_versions_projects
      sql_on: "${production_management_1_post_acceptance_bug_projects.project_name} = ${production_management_1_milestone_versions_projects.project_name}"
      relationship: one-to-one
  columns:
  - name: id
    description: "Cột Id trong Bug sau nghiệm thu- Projects."
    meta:
      dimension:
        type: number
        label: "Id"
        hidden: true
  - name: project_name
    description: "Cột PROJECT_NAME trong Bug sau nghiệm thu- Projects."
    meta:
      dimension:
        type: string
        label: "PROJECT_NAME"
        hidden: true
