version: 2
sources:
- name: pbi_silver__production_management_1
  database: hive
  schema: "{{ env_var('DBT_TRINO_SCHEMA', 'pbi_silver') }}"
  description: "Silver layer sources for domain: production_management_1"
  tables:
  - name: production_management_1_mm_qa_fixversion
    description: "Nguồn Power BI: mm_QA_fixversion"
    columns:
    - name: product_service
      description: "Cột Sản phẩm/dịch vụ"
    - name: man_month
      description: "Cột man month"
    - name: date_value
      description: "Cột ngày tháng"
    - name: working_days
      description: "Cột Số ngày làm việc"
    - name: md_qa
      description: "Cột md_QA"
