version: 2
sources:
- name: pbi_silver__production_management_1
  database: hive
  schema: "{{ env_var('DBT_TRINO_SCHEMA', 'pbi_silver') }}"
  description: "Silver layer sources for domain: production_management_1"
  tables:
  - name: production_management_1_acceptance_bug
    description: "Nguồn Power BI: Bug nghiệm thu"
    columns:
    - name: id
      description: "Cột Id"
    - name: issue_summary
      description: "Cột ISSUE_SUMMARY"
    - name: issue_created
      description: "Cột ISSUE_CREATED"
    - name: issue_project_id
      description: "Cột ISSUE_PROJECT_ID"
    - name: issue_current_type_name
      description: "Cột ISSUE_CURRENT_TYPE_NAME"
