version: 2
sources:
- name: pbi_silver__production_management_1
  database: hive
  schema: "{{ env_var('DBT_TRINO_SCHEMA', 'pbi_silver') }}"
  description: "Silver layer sources for domain: production_management_1"
  tables:
  - name: production_management_1_done_charter
    description: "Nguồn Power BI: Done charter"
    columns:
    - name: id
      description: "Cột Id"
    - name: issue_key
      description: "Cột ISSUE_KEY"
    - name: issue_resolved
      description: "Cột ISSUE_RESOLVED"
    - name: issue_created
      description: "Cột ISSUE_CREATED"
    - name: issue_summary
      description: "Cột ISSUE_SUMMARY"
    - name: issue_current_status_name
      description: "Cột ISSUE_CURRENT_STATUS_NAME"
    - name: issue_current_status_category_name
      description: "Cột ISSUE_CURRENT_STATUS_CATEGORY_NAME"
    - name: issue_project_id
      description: "Cột ISSUE_PROJECT_ID"
    - name: center
      description: "Cột Trung tâm"
    - name: date_value
      description: "Cột Date"
    - name: issue_key_prefix
      description: "Cột ISSUE_KEY_PREFIX"
    - name: project_name
      description: "Cột PROJECT NAME"
    - name: issue_time_spent_with_st
      description: "Cột ISSUE_TIME_SPENT_WITH_ST"
