name: 'planview_epm_dw'
version: '1.0.0'
config-version: 2

# Profile connecting to Trino (hive catalog)
profile: 'trino_hive'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  planview_epm_dw:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      core:
        +materialized: table
        +schema: marts_core
      evm:
        +materialized: incremental
        +schema: marts_evm
