CREATE TABLE IF NOT EXISTS hr_raw.hr_employee_onboard (
  employee_id STRING COMMENT 'Employee code / HR business key',
  employee_name STRING COMMENT 'Full name of employee',
  status STRING COMMENT 'Current employment status',
  hire_status STRING COMMENT 'New hire status',
  employee_group STRING COMMENT 'Employee object/group',
  contract_company_type STRING COMMENT 'Contract type (independent company or internal)',
  branch_name STRING COMMENT 'Branch name',
  division_name STRING COMMENT 'Division / block name',
  n1_group STRING COMMENT 'Organization level N',
  n2_group STRING COMMENT 'Organization level N-1',
  job_title STRING COMMENT 'Job title / role base',
  employee_level STRING COMMENT 'Employee level',
  regional_staff STRING COMMENT 'Region / working area',
  management_level STRING COMMENT 'Management hierarchy level',
  previous_independent_company_type STRING COMMENT 'Previous contract type before independent company',
  hire_date STRING COMMENT 'Hire date',
  hire_date_vcs STRING COMMENT 'Hire date at VCS',
  termination_date STRING COMMENT 'Termination / resignation date',
  business_email STRING COMMENT 'Business email address',
  dob STRING COMMENT 'Date of birth',
  gender STRING COMMENT 'Gender',
  tenure_group STRING COMMENT 'Tenure group',
  pr_q1_2024 STRING COMMENT 'Performance review score Q1 2024',
  pr_q2_2024 STRING COMMENT 'Performance review score Q2 2024',
  pr_q3_2024 STRING COMMENT 'Performance review score Q3 2024',
  pr_q4_2024 STRING COMMENT 'Performance review score Q4 2024',
  pr_avg_2024 STRING COMMENT 'Average performance review score 2024',
  pr_q1_2025 STRING COMMENT 'Performance review score Q1 2025',
  pr_q2_2025 STRING COMMENT 'Performance review score Q2 2025',
  achievement_title_2024 STRING COMMENT 'Achievement / award title in 2024',
  talent_group STRING COMMENT '9-box or talent group classification',
  manager_comment STRING COMMENT 'Manager comment',
  termination_status STRING COMMENT 'Termination status',
  termination_reason_1 STRING COMMENT 'Primary termination reason',
  termination_reason_2 STRING COMMENT 'Secondary termination reason',
  termination_detail_reason STRING COMMENT 'Detailed termination reason',
  termination_additional_info STRING COMMENT 'Additional termination information from HR or manager',
  recommendation STRING COMMENT 'Recommendation note',
  high_potential_factor STRING COMMENT 'High-potential human resource factors',
  next_workplace STRING COMMENT 'Next workplace after leaving',
  exit_interviewer STRING COMMENT 'Exit interview owner',
  pr_q3_2025 STRING COMMENT 'Performance review score Q3 2025',
  start_month STRING COMMENT 'Start month of period',
  end_month STRING COMMENT 'End month of period',

  t1 STRING COMMENT 'Technical / evaluation metric T1',
  t2 STRING COMMENT 'Technical / evaluation metric T2',
  t3 STRING COMMENT 'Technical / evaluation metric T3',
  t4 STRING COMMENT 'Technical / evaluation metric T4',
  t5 STRING COMMENT 'Technical / evaluation metric T5',
  t6 STRING COMMENT 'Technical / evaluation metric T6',
  t7 STRING COMMENT 'Technical / evaluation metric T7',
  t8 STRING COMMENT 'Technical / evaluation metric T8',
  t9 STRING COMMENT 'Technical / evaluation metric T9',
  t10 STRING COMMENT 'Technical / evaluation metric T10',
  t11 STRING COMMENT 'Technical / evaluation metric T11',
  t12 STRING COMMENT 'Technical / evaluation metric T12',

  is_new_hire STRING COMMENT 'Is new hire indicator',
  voluntary_exit STRING COMMENT 'Voluntary resignation indicator',
  company_termination STRING COMMENT 'Company initiated termination indicator',
  new_hire_and_voluntary_exit STRING COMMENT 'New hire and voluntary exit flag',
  new_hire_and_company_termination STRING COMMENT 'New hire and company termination flag',

  q1 STRING COMMENT 'Quarter 1 indicator',
  q2 STRING COMMENT 'Quarter 2 indicator',
  q3 STRING COMMENT 'Quarter 3 indicator',
  q4 STRING COMMENT 'Quarter 4 indicator',

  q1__bn STRING COMMENT 'Derived metric Q1 (BN)',
  q2__bo STRING COMMENT 'Derived metric Q2 (BO)',
  q3__bp STRING COMMENT 'Derived metric Q3 (BP)',
  q4__bq STRING COMMENT 'Derived metric Q4 (BQ)',

  hire_age STRING COMMENT 'Age at hire time',
  portfolio STRING COMMENT 'Portfolio / specialization',
  n3_group STRING COMMENT 'Organization level N-2',
  job_family STRING COMMENT 'Job family',

  t1__bv STRING COMMENT 'Derived metric T1 (BV)',
  t2__bw STRING COMMENT 'Derived metric T2 (BW)',
  t3__bx STRING COMMENT 'Derived metric T3 (BX)',
  t4__by STRING COMMENT 'Derived metric T4 (BY)',
  t5__bz STRING COMMENT 'Derived metric T5 (BZ)',
  t6__ca STRING COMMENT 'Derived metric T6 (CA)',
  t7__cb STRING COMMENT 'Derived metric T7 (CB)',
  t8__cc STRING COMMENT 'Derived metric T8 (CC)',
  t9__cd STRING COMMENT 'Derived metric T9 (CD)',
  t10__ce STRING COMMENT 'Derived metric T10 (CE)',
  t11__cf STRING COMMENT 'Derived metric T11 (CF)',
  t12__cg STRING COMMENT 'Derived metric T12 (CG)',

  nan STRING COMMENT 'Unknown / empty source column',
  t1__ci STRING COMMENT 'Derived metric T1 (CI)',
  t2__cj STRING COMMENT 'Derived metric T2 (CJ)',
  t3__ck STRING COMMENT 'Derived metric T3 (CK)',
  t4__cl STRING COMMENT 'Derived metric T4 (CL)',
  t5__cm STRING COMMENT 'Derived metric T5 (CM)',
  t6__cn STRING COMMENT 'Derived metric T6 (CN)',
  t7__co STRING COMMENT 'Derived metric T7 (CO)',
  t8__cp STRING COMMENT 'Derived metric T8 (CP)',
  t9__cq STRING COMMENT 'Derived metric T9 (CQ)',
  t10__cr STRING COMMENT 'Derived metric T10 (CR)',
  t11__cs STRING COMMENT 'Derived metric T11 (CS)',
  t12__ct STRING COMMENT 'Derived metric T12 (CT)',

  nan__cu STRING COMMENT 'Unknown / empty derived column',

  t1__cv STRING COMMENT 'Derived metric T1 (CV)',
  t2__cw STRING COMMENT 'Derived metric T2 (CW)',
  t3__cx STRING COMMENT 'Derived metric T3 (CX)',
  t4__cy STRING COMMENT 'Derived metric T4 (CY)',
  t5__cz STRING COMMENT 'Derived metric T5 (CZ)',
  t6__da STRING COMMENT 'Derived metric T6 (DA)',
  t7__db STRING COMMENT 'Derived metric T7 (DB)',
  t8__dc STRING COMMENT 'Derived metric T8 (DC)',
  t9__dd STRING COMMENT 'Derived metric T9 (DD)',
  t10__de STRING COMMENT 'Derived metric T10 (DE)',
  t11__df STRING COMMENT 'Derived metric T11 (DF)',
  t12__dg STRING COMMENT 'Derived metric T12 (DG)',

  core_position STRING COMMENT 'Core position flag',
  pr_avg_q_1_2_2025 STRING COMMENT 'Average PR score Q1–Q2 2025',
  pr_near_fail_count_q3_2024_q2_2025 STRING COMMENT 'Count of near-fail PR from Q3 2024 to Q2 2025',
  pr_near_fail_count_q1_q2_2025 STRING COMMENT 'Count of near-fail PR Q1–Q2 2025',
  pr_exceed_count_q3_2024_q2_2025 STRING COMMENT 'Count of exceed PR from Q3 2024 to Q2 2025',
  pr_exceed_count_q1_q2_2025 STRING COMMENT 'Count of exceed PR Q1–Q2 2025',
  cp_result_round_1_2025 STRING COMMENT 'CP result round 1 – 2025',
  cp_recommendation_round_2_2025 STRING COMMENT 'CP recommendation round 2 – 2025',
  recognition_count STRING COMMENT 'Recognition count',
  recognition_6_months STRING COMMENT 'Recognition in last 6 months',
  is_development_focus_employee STRING COMMENT 'Development focus employee flag',
  is_properly_recognized_employee STRING COMMENT 'Properly recognized employee flag',
  high_pr_without_recognition_flag STRING COMMENT 'High PR but not recognized flag',
  low_pr_but_recognized_flag STRING COMMENT 'Low PR but recognized flag',
  is_core_employee STRING COMMENT 'Core employee flag',
  age STRING COMMENT 'Current age',
  key STRING COMMENT 'Key employee indicator',
  hp STRING COMMENT 'High potential indicator',
  key_hp STRING COMMENT 'Key & high potential indicator',
  is_core_employee__ea STRING COMMENT 'Derived core employee flag',

  crawled_at_ts BIGINT COMMENT 'Crawl timestamp (epoch)',
  hire_date_ts BIGINT COMMENT 'Hire date timestamp (epoch)',
  hire_date_vcs_ts BIGINT COMMENT 'Hire date VCS timestamp (epoch)',
  dob_ts BIGINT COMMENT 'Date of birth timestamp (epoch)',
  termination_date_ts BIGINT COMMENT 'Termination date timestamp (epoch)'
)
COMMENT 'Raw HR employee onboarding table (snapshot from source system)'
STORED AS PARQUET
LOCATION 's3a://vcs-raw/hr-raw/hr_employee_onboard';
