(
    SYSID STRING,
    Name STRING,
    Description STRING,
    CreatedBy STRING,
    C_Assignor STRING,
    C_Assignee STRING,
    C_StartDate DATE,
    C_EndDate DATE,
    C_ParentAssignment STRING,
    C_Department STRING,
    EntityOwner STRING,
    C_AchievementRate DOUBLE,
    C_TotalWeight DOUBLE,
    C_SumTargetWeightPercent DOUBLE,
    LastUpdatedOn DATE,
    LastUpdatedBySystemOn DATE,
    CreatedOn DATE,
    ExternalID STRING,
    EntityType STRING
)
