name: 'hr'
version: '1.0.0'
profile: 'hr'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  hr:
    +materialized: "{{ env_var('DBT_MATERIALIZED', 'ephemeral') }}"
    +schema: "{{ env_var('DBT_TRINO_SCHEMA', 'bi_gold') }}"
    +tags: ['hr']
    +meta:
      openmetadata:
        service: hr-gold