
CREATE SCHEMA IF NOT EXISTS hive.personal_raw;

CREATE TABLE IF NOT EXISTS hive.personal_raw.c_assignments (
  c_countof_sub_assignments DOUBLE,
  c_achievement_rate DOUBLE,
  c_assignee VARCHAR,
  c_assignment_number VARCHAR,
  c_assignor VARCHAR,
  c_department VARCHAR,
  c_end_date DATE,
  c_essential_weight_total_percent DOUBLE,
  c_parent_assignment VARCHAR,
  c_reporter VARCHAR,
  c_start_date DATE,
  c_sum_target_weight_percent DOUBLE,
  c_sum_target_result_weight_all DOUBLE,
  c_sum_target_w_result_compliance DOUBLE,
  c_total_assignment_weight_result DOUBLE,
  c_total_weight DOUBLE,
  c_update_description VARCHAR,
  c_weight_bonus DOUBLE,
  c_weight_bonus_description VARCHAR,
  c_weight_collaboration DOUBLE,
  c_weight_collaboration_description VARCHAR,
  c_weight_compliance DOUBLE,
  c_weight_policy DOUBLE,
  c_weight_policy_description VARCHAR,
  emails_count DOUBLE,
  created_by VARCHAR,
  created_on DATE,
  currency_exchange_date DATE,
  default_integration_path VARCHAR,
  description VARCHAR,
  external_id VARCHAR,
  sysid VARCHAR,
  image_url VARCHAR,
  entity_type VARCHAR,
  last_updated_by VARCHAR,
  last_updated_on DATE,
  name VARCHAR,
  entity_owner VARCHAR,
  last_updated_by_system_on DATE,
   _raw_payload VARCHAR,
   _batch_id VARCHAR,
   _ingest_timestamp TIMESTAMP(6),
  ingest_date DATE
)
WITH (
    format = 'PARQUET',
    external_location = '/opt/datasets/crawlers/vcs/clarizen/data/personal_raw/c_assignments'
);


CREATE SCHEMA IF NOT EXISTS hive.global_clean;

CREATE TABLE IF NOT EXISTS hive.global_clean.c_assignments (
  c_countof_sub_assignments DOUBLE,
  c_achievement_rate DOUBLE,
  c_assignee VARCHAR,
  c_assignment_number VARCHAR,
  c_assignor VARCHAR,
  c_department VARCHAR,
  c_end_date DATE,
  c_essential_weight_total_percent DOUBLE,
  c_parent_assignment VARCHAR,
  c_reporter VARCHAR,
  c_start_date DATE,
  c_sum_target_weight_percent DOUBLE,
  c_sum_target_result_weight_all DOUBLE,
  c_sum_target_w_result_compliance DOUBLE,
  c_total_assignment_weight_result DOUBLE,
  c_total_weight DOUBLE,
  c_update_description VARCHAR,
  c_weight_bonus DOUBLE,
  c_weight_bonus_description VARCHAR,
  c_weight_collaboration DOUBLE,
  c_weight_collaboration_description VARCHAR,
  c_weight_compliance DOUBLE,
  c_weight_policy DOUBLE,
  c_weight_policy_description VARCHAR,
  emails_count DOUBLE,
  created_by VARCHAR,
  created_on DATE,
  currency_exchange_date DATE,
  default_integration_path VARCHAR,
  description VARCHAR,
  external_id VARCHAR,
  sysid VARCHAR,
  image_url VARCHAR,
  entity_type VARCHAR,
  last_updated_by VARCHAR,
  last_updated_on DATE,
  name VARCHAR,
  entity_owner VARCHAR,
  last_updated_by_system_on DATE,
   _batch_id VARCHAR,
   _ingest_timestamp TIMESTAMP(6),
  ingest_date DATE
)
WITH (
    format = 'PARQUET',
    external_location = '/opt/datasets/crawlers/vcs/clarizen/data/global_clean/c_assignments'
);
