-- Spark SQL DDL cho bang 'objective' (51 cot tu data_type/)
-- Chay tren Zeppelin (%spark.sql).
-- Bang KHONG partition: dat thang cac file .parquet vao LOCATION.
-- 'ingest_date' la cot DATE binh thuong nam trong file.

CREATE DATABASE IF NOT EXISTS personal_raw;

DROP TABLE IF EXISTS personal_raw.objective;

CREATE TABLE personal_raw.objective (
    c_assignee STRING,
    c_associated_contributions STRING,
    c_associated_departments_portfolio STRING,
    c_calculate_progress STRING,
    c_department STRING,
    c_description STRING,
    c_n1_result_response STRING,
    c_normalized_score DOUBLE,
    c_objective_progress_m STRING,
    c_objective_progress_n STRING,
    c_objective_type STRING,
    c_planned_revenue_m_rollup DOUBLE,
    c_planned_revenue_n_rollup DOUBLE,
    c_record_type STRING,
    c_reporter STRING,
    c_tot_plan_cont_rollup_m DOUBLE,
    c_tot_plan_cont_rollup_n DOUBLE,
    c_total_planned_objectives_m DOUBLE,
    c_total_planned_objectives_n DOUBLE,
    c_total_planned_target_m DOUBLE,
    c_total_planned_target_n DOUBLE,
    c_total_weight_assignments DOUBLE,
    c_total_weight_percentage DOUBLE,
    c_trigger_wfr DOUBLE,
    c_trigger_wr BOOLEAN,
    attachments_count DOUBLE,
    emails_count DOUBLE,
    notes_count DOUBLE,
    sub_objectives_count DOUBLE,
    percent_of_plan DOUBLE,
    actual_percent DOUBLE,
    entity_owner STRING,
    associated_item STRING,
    created_by STRING,
    created_on DATE,
    currency_exchange_date DATE,
    description STRING,
    end_date DATE,
    external_id STRING,
    sysid STRING,
    entity_type STRING,
    last_updated_by STRING,
    last_updated_on DATE,
    name STRING,
    parent_objective STRING,
    planned_percent DOUBLE,
    start_date DATE,
    state STRING,
    status STRING,
    last_updated_by_system_on DATE,
    weight DOUBLE,
    _raw_payload STRING,
    _batch_id STRING,
    _ingest_timestamp TIMESTAMP,
    ingest_date DATE
)
USING PARQUET
LOCATION '/opt/datasets/crawlers/vcs/clarizen/data/personal_raw/objective';

CREATE DATABASE IF NOT EXISTS global_clean;

DROP TABLE IF EXISTS global_clean.objective;

CREATE TABLE global_clean.objective (
    c_assignee STRING,
    c_associated_contributions STRING,
    c_associated_departments_portfolio STRING,
    c_calculate_progress STRING,
    c_department STRING,
    c_description STRING,
    c_n1_result_response STRING,
    c_normalized_score DOUBLE,
    c_objective_progress_m STRING,
    c_objective_progress_n STRING,
    c_objective_type STRING,
    c_planned_revenue_m_rollup DOUBLE,
    c_planned_revenue_n_rollup DOUBLE,
    c_record_type STRING,
    c_reporter STRING,
    c_tot_plan_cont_rollup_m DOUBLE,
    c_tot_plan_cont_rollup_n DOUBLE,
    c_total_planned_objectives_m DOUBLE,
    c_total_planned_objectives_n DOUBLE,
    c_total_planned_target_m DOUBLE,
    c_total_planned_target_n DOUBLE,
    c_total_weight_assignments DOUBLE,
    c_total_weight_percentage DOUBLE,
    c_trigger_wfr DOUBLE,
    c_trigger_wr BOOLEAN,
    attachments_count DOUBLE,
    emails_count DOUBLE,
    notes_count DOUBLE,
    sub_objectives_count DOUBLE,
    percent_of_plan DOUBLE,
    actual_percent DOUBLE,
    entity_owner STRING,
    associated_item STRING,
    created_by STRING,
    created_on DATE,
    currency_exchange_date DATE,
    description STRING,
    end_date DATE,
    external_id STRING,
    sysid STRING,
    entity_type STRING,
    last_updated_by STRING,
    last_updated_on DATE,
    name STRING,
    parent_objective STRING,
    planned_percent DOUBLE,
    start_date DATE,
    state STRING,
    status STRING,
    last_updated_by_system_on DATE,
    weight DOUBLE,
    _batch_id STRING,
    _ingest_timestamp TIMESTAMP,
    ingest_date DATE
)
USING PARQUET
LOCATION '/opt/datasets/crawlers/vcs/clarizen/data/global_clean/objective';
