version: "3.9"

networks:
  authelia-proxy-external:
    external: true

# ================= COMMON CONFIG =================
x-common-service: &common-service
  image: ingestions:latest
  restart: always
  volumes:
    - .:/app
    - /u01/trino-server-479/etc/zeppelin.server.kerberos.keytab:/etc/security/zeppelin.keytab:ro
    - /etc/krb5.conf:/etc/krb5.conf:ro
  env_file: .env.prod
  environment:
    PREFECT_API_URL: http://prefect-server:4200/api
    HTTP_PROXY: 
    HTTPS_PROXY: 
    http_proxy: 
    https_proxy: 
  extra_hosts: &common-hosts
    - "prefect-external.viettelcyber.com:10.254.130.46"
    - "manager.sdm.viettelcyber.com:10.254.130.48"
    - "onefs.sdm.viettelcyber.com:10.254.132.2"
    - "web.sdm.viettelcyber.com:10.254.130.46"
    - "master.sdm.viettelcyber.com:10.254.130.47"
    - "data.sdm.viettelcyber.com:10.254.130.46"
    - "zeppeline.sdm.viettelcyber.com:10.254.130.46"
    - "datalake.viettelcyber.com:10.254.130.46"
    - "datalake-s3.viettelcyber.com:10.255.244.100"
    - "nocodb.viettelcyber.com:10.255.244.100"
  networks:
    - authelia-proxy-external
  logging:
    driver: "json-file"
    options:
      max-size: "50m"
      max-file: "10"

x-kerberos-command: &kerberos-command
  bash -c "
    kinit -kt /etc/security/zeppelin.keytab zeppelin-datamining@SDM.VIETTELCYBER.COM &&
    python {{SCRIPT}}
  "

# ================= SERVICES =================
services:

  test_minio_flow:
    <<: *common-service
    container_name: test_minio_flow
    security_opt:
      - seccomp=unconfined
    command: >
      bash -c "
        kinit -kt /etc/security/zeppelin.keytab zeppelin-datamining@SDM.VIETTELCYBER.COM &&
        python test_minio_flow.py
      "

  test_hdfs_flow:
    <<: *common-service
    container_name: test_hdfs_flow
    security_opt:
      - seccomp=unconfined
    command: >
      bash -c "
        kinit -kt /etc/security/zeppelin.keytab zeppelin-datamining@SDM.VIETTELCYBER.COM &&
        python test_hdfs_flow.py
      "

  # freshworks-crawler:
  #   <<: *common-service
  #   container_name: crm
  #   environment:
  #     PREFECT_API_URL: http://prefect-server:4200/api
  #     KRB5_CLIENT_KTNAME: /etc/security/zeppelin.keytab
  #   command: >
  #     bash -c "
  #       kinit -kt /etc/security/zeppelin.keytab zeppelin-datamining@SDM.VIETTELCYBER.COM &&
  #       python freshworks_crawler_flow.py
  #     "

  # jira-crawler:
  #   <<: *common-service
  #   container_name: jira
  #   command: >
  #     bash -c "
  #       kinit -kt /etc/security/zeppelin.keytab zeppelin-datamining@SDM.VIETTELCYBER.COM &&
  #       python jira_crawler_flow.py
  #     "

  # noc-metrics-crawler:
  #   <<: *common-service
  #   container_name: noc-metrics
  #   command: >
  #     bash -c "
  #       kinit -kt /etc/security/zeppelin.keytab zeppelin-datamining@SDM.VIETTELCYBER.COM &&
  #       python noc_crawler_flow.py
  #     "

  kpi_kpq_nocodb_flow:
    <<: *common-service
    container_name: kpi_kqi_nocodb
    security_opt:
      - seccomp=unconfined
    command: >
      bash -c "
        kinit -kt /etc/security/zeppelin.keytab zeppelin-datamining@SDM.VIETTELCYBER.COM &&
        python kpi_kpq_nocodb_flow.py
      "