FROM node:20-bookworm-slim

ENV HTTP_PROXY=http://192.168.5.8:3128
ENV HTTPS_PROXY=http://192.168.5.8:3128
ENV NO_PROXY=localhost,127.0.0.1,.internal,.svc,10.0.0.0/8,10.255.245.150,*.viettelcyber.com,192.168.47.128,db,minio,lightdash,trino.viettelcyber.com,ai-gateway.viettelcyber.com
ENV no_proxy=localhost,127.0.0.1,.internal,.svc,10.0.0.0/8,10.255.245.150,*.viettelcyber.com,192.168.47.128,db,minio,lightdash,trino.viettelcyber.com,ai-gateway.viettelcyber.com

RUN echo "Acquire::http::Proxy \"${http_proxy}\";" > /etc/apt/apt.conf.d/01proxy && \
    echo "Acquire::https::Proxy \"${https_proxy}\";" >> /etc/apt/apt.conf.d/01proxy && \
    echo "Acquire::https::Verify-Peer \"false\";" >> /etc/apt/apt.conf.d/01proxy && \
    echo "Acquire::https::Verify-Host \"false\";" >> /etc/apt/apt.conf.d/01proxy

RUN apt-get -o Acquire::https::Verify-Peer=false update \
    && apt-get -o Acquire::https::Verify-Peer=false install -y --no-install-recommends \
       python3 \
       python3-pip \
       python3-venv \
       ca-certificates \
       bash \
    && rm -rf /var/lib/apt/lists/*

# ===== Config pip (proxy + ignore SSL) =====
RUN pip3 config set global.proxy ${http_proxy} && \
    pip3 config set global.trusted-host "pypi.org files.pythonhosted.org" && \
    pip3 config set global.cert false

RUN pip3 install --no-cache-dir dbt-core dbt-trino
RUN npm install -g @lightdash/cli@latest

WORKDIR /workspace
COPY . /workspace

RUN chmod +x /workspace/scripts/setup-lightdash-projects.sh
ENTRYPOINT ["/workspace/scripts/setup-lightdash-projects.sh"]
