coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080

query.max-memory=512MB
query.max-memory-per-node=512MB
memory.heap-headroom-per-node=200MB


discovery.uri=http://trino:8080

http-server.threads.max=10