node.environment=dev
node.id=115dc01a-4a00-41d0-81a1-24102903add3
node.data-dir=/u01/data/bi-trino-479
node.internal-address=trino

#http-server.authentication.type=NONE
#web-ui.authentication.type=NONE

http-server.authentication.type=PASSWORD
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=etc/keystore.jks
http-server.https.keystore.key=Welcome1
http-server.authentication.allow-insecure-over-http=true
internal-communication.shared-secret=Welcome1
# http-server.authentication.allow-insecure-over-http=true