CREATE TABLE IF NOT EXISTS hr_raw.hr_training_class_list (
    sequence_number VARCHAR,
    updated_date VARCHAR,
    organizing_unit VARCHAR,
    pic VARCHAR,
    class_code VARCHAR,
    class_name VARCHAR,
    course_name VARCHAR,
    training_program VARCHAR,
    training_method VARCHAR,
    program_group VARCHAR,
    training_format VARCHAR,
    class_status VARCHAR,
    training_duration VARCHAR,
    start_date VARCHAR,
    end_date VARCHAR,
    month VARCHAR,
    year VARCHAR,
    planned_learner_count VARCHAR,
    actual_learner_count VARCHAR,
    training_hours VARCHAR,
    training_content VARCHAR,
    instructor_name VARCHAR,
    organization_rating VARCHAR,
    average_rating VARCHAR,
    level_2_evaluation VARCHAR,
    pass_rate VARCHAR,
    lxp_status_note VARCHAR,
    updated_date_ts BIGINT,
    start_date_ts BIGINT,
    end_date_ts BIGINT,
    snapshot_date VARCHAR,
    snapshot_date_ts BIGINT,
    filename VARCHAR,
    crawled_at_ts BIGINT
)
WITH (
   external_location = 's3a://vcs-raw/hr-raw/hr_training_class_list',
   format = 'PARQUET'
);