version: "3.9"
# docker network create  authelia-proxy-internal
networks:
  # authelia-proxy-internal:
  #   external: true
  workflow_authelia-proxy-internal:
    external: true

# ================= COMMON CONFIG =================
x-common-service: &common-service
  # docker build -f Dockerfile.ambari -t flow-external-ingestions:latest .
  image: flow-external-ingestions:latest
  restart: always
  volumes:
    - .:/app
  env_file: .env.ambari
  environment:
    PREFECT_API_URL: http://prefect-server:4200/api
    HTTP_PROXY: 
    HTTPS_PROXY: 
    http_proxy: 
    https_proxy: 
  extra_hosts: &common-hosts
    - "prefect-external.viettelcyber.com:10.254.130.46"
    - "datalake.viettelcyber.com:10.255.244.100"
    - "datalake-s3.viettelcyber.com:10.255.244.100"
    - "nocodb.viettelcyber.com:10.255.244.100"
    - "trino.viettelcyber.com:10.255.244.100"
    - "secagi.viettelcyber.com:10.255.244.100"
  networks:
    - workflow_authelia-proxy-internal
  logging:
    driver: "json-file"
    options:
      max-size: "50m"
      max-file: "10"


# ================= SERVICES =================
services:

  # hdfs-test_minio_flow:
  #   <<: *common-service
  #   container_name: hdfs-test_minio_flow
  #   security_opt:
  #     - seccomp=unconfined
  #   command: >
  #     bash -c "
  #       python test_minio_flow.py
  #     "

  # hdfs-test_hdfs_flow:
  #   <<: *common-service
  #   container_name: hdfs-test_hdfs_flow
  #   security_opt:
  #     - seccomp=unconfined
  #   command: >
  #     bash -c "
  #       python test_hdfs_flow.py
  #     "

  ambari-hdfs-jira-crawler:
    <<: *common-service
    container_name: ambari-hdfs-jira-crawler
    command: >
      bash -c "
        python jira_crawler_flow.py
      "

  ambari-hdfs-noc-metrics-crawler:
    <<: *common-service
    container_name: ambari-hdfs-noc-metrics-crawler
    command: >
      bash -c "
        python noc_crawler_flow.py
      "

  # ambari-hdfs-kpi_kpq_nocodb_flow:
  #   <<: *common-service
  #   container_name: ambari-hdfs-kpi_kpq_nocodb_flow
  #   security_opt:
  #     - seccomp=unconfined
  #   command: >
  #     bash -c "
  #       python kpi_kpq_nocodb_flow.py
  #     "
  
  # ambari-ambari-freshworks-crawler:
  #   <<: *common-service
  #   container_name: ambari-freshworks-crawler
  #   command: >
  #     bash -c "
  #       python freshworks_crawler_flow_ambari.py
  #     "

  ambari-cx-survicate-crawler:
    <<: *common-service
    container_name: ambari-cx-survicate-crawler
    command: >
      bash -c "
        python cx_survicate_crawler_flow_ambari.py
      "

  ambari-cx-cso-crawler:
    <<: *common-service
    container_name: ambari-cx-cso-crawler
    command: >
      bash -c "
        python cx_cso_crawler_flow_ambari.py
      "
  ambari-mixpanel-crawler-flow:
    <<: *common-service
    container_name: ambari-mixpanel-crawler-flow
    command: >
      bash -c "
        python mixpanel_crawler_flow_ambari.py
      "
