CREATE TABLE IF NOT EXISTS cx_cso_raw.raw_dim_cso_contacts (
          active BOOLEAN,
  address STRING,
  description STRING,
  email STRING,
  id BIGINT,
  job_title STRING,
  language STRING,
  mobile STRING,
  name STRING,
  phone STRING,
  time_zone STRING,
  twitter_id STRING,
  custom_fields STRUCT<language_mail:STRING, gender:STRING, contact_segment:STRING>,
  facebook_id STRING,
  created_at STRING,
  updated_at STRING,
  csat_rating BIGINT,
  preferred_source STRING,
  company_id BIGINT,
  unique_external_id STRING,
  first_name STRING,
  last_name STRING,
  visitor_id STRING,
  org_contact_id BIGINT,
  org_contact_id_str STRING,
  other_phone_numbers ARRAY<STRUCT<label:STRING, value:STRING>>,
  created_at_ts BIGINT,
  updated_at_ts BIGINT,
  company STRUCT<id:BIGINT, view_all_tickets:BOOLEAN, name:STRING, avatar:STRING, org_company_id:STRING>,
  other_companies ARRAY<STRING>,
  crawled_at_ts BIGINT
        )
        USING PARQUET
        LOCATION 's3a://vcs-raw/cx-cso-raw/dim_cso_contacts'