CREATE TABLE IF NOT EXISTS cx_cso_raw.raw_fact_cso_tickets (
          cc_emails ARRAY<STRING>,
  fwd_emails ARRAY<STRING>,
  reply_cc_emails ARRAY<STRING>,
  ticket_cc_emails ARRAY<STRING>,
  ticket_bcc_emails ARRAY<STRING>,
  fr_escalated BOOLEAN,
  spam BOOLEAN,
  email_config_id BIGINT,
  group_id BIGINT,
  priority BIGINT,
  requester_id BIGINT,
  responder_id BIGINT,
  source BIGINT,
  company_id BIGINT,
  status BIGINT,
  subject STRING,
  association_type BIGINT,
  support_email STRING,
  to_emails ARRAY<STRING>,
  product_id BIGINT,
  id BIGINT,
  type STRING,
  due_by STRING,
  fr_due_by STRING,
  is_escalated BOOLEAN,
  custom_fields STRUCT<cf_nh_gi_mc_x_l:STRING, cf_chng_trnh_hng_ng:STRING, cf_onehourbeforedue:BOOLEAN, cf_twothirdtime:BOOLEAN, cf_onedaybeforedue:BOOLEAN, cf_legacy_id:STRING, cf_reason:STRING, cf_thirdfourtime:BOOLEAN, cf_spam_type:STRING, cf_rt_notification:BOOLEAN, cf__l1_violated:STRING, cf__l2_violated:STRING, cf__l3_violated:STRING, cf__l4_violated:STRING, cf__l2:STRING, cf__l3:STRING, cf__l4:STRING, cf__call_reminder:STRING, cf__isvcs:BOOLEAN, cf_incident_root_cause:STRING, cf_company:STRING, cf_severity:STRING, cf_exception:STRING, cf_imported_ticket_id:STRING, cf_sentiment:STRING, cf_recent_note:STRING, cf_urgency:STRING, cf_rt_overdue:STRING, cf_ttr_overdue:STRING, cf_old_due_date:STRING, cf_hiu_qu_trao_i:STRING, cf_customer_respond_date:STRING, cf_link_kb:STRING, cf_issues_type:STRING, cf_rt_time:STRING, cf_number_of_due_date_changes:BIGINT, cf_note:STRING, cf_reminder_update:BOOLEAN, cf_csat_rating:BIGINT, cf_timer_history:STRING, cf_product_category:STRING, cf__ticket_cx_report:BOOLEAN, cf__segment:STRING, cf__merge:STRING, cf_agent_l1:STRING, cf__l1_time_allowed:STRING, cf__components:STRING, cf_hide_field:STRING, cf_component:STRING, cf_subtype:STRING, cf__l1_time_actual:STRING, cf__l2_time_allowed:STRING, cf__l2_time_actual:STRING, cf__l3_time_allowed:STRING, cf__l3_time_actual:STRING, cf__l4_time_allowed:STRING, cf_l1:BOOLEAN, cf_imported_ticket_date:STRING, cf__l4_time_actual:STRING, cf_l2:BOOLEAN, cf_l3:BOOLEAN, cf_ai_sentiment:STRING, cf_l4:BOOLEAN, cf_related_ticket:STRING, cf_ttr_time:STRING, cf_imported_ticket_due_date:STRING, cf_imported_ticket_link:STRING, cf_customer_entry_channel:STRING>,
  created_at STRING,
  updated_at STRING,
  associated_tickets_count BIGINT,
  tags ARRAY<STRING>,
  description STRING,
  description_text STRING,
  requester STRUCT<id:BIGINT, name:STRING, email:STRING, mobile:STRING, phone:STRING>,
  stats STRUCT<agent_responded_at:STRING, requester_responded_at:STRING, first_responded_at:STRING, status_updated_at:STRING, reopened_at:STRING, resolved_at:STRING, closed_at:STRING, pending_since:STRING>,
  structured_description STRING,
  company STRUCT<_dummy_:BIGINT, id:BIGINT, name:STRING>,
  nr_due_by STRING,
  nr_escalated BOOLEAN,
  due_by_ts BIGINT,
  fr_due_by_ts BIGINT,
  created_at_ts BIGINT,
  updated_at_ts BIGINT,
  form_id BIGINT,
  crawled_at_ts BIGINT
        )
        USING PARQUET
        LOCATION 's3a://vcs-raw/cx-cso-raw/fact_cso_tickets'