DROP TABLE IF EXISTS cx_cso_raw.fact_cso_tickets


CREATE TABLE  NOT EXISTS  cx_cso_raw.fact_cso_tickets (
associated_tickets_count BIGINT,
associated_tickets_list ARRAY<BIGINT>,
association_type BIGINT,
attachments ARRAY<STRUCT<attachment_url:STRING,content_type:STRING,created_at:STRING,id:BIGINT,name:STRING,size:BIGINT,updated_at:STRING>>,
cc_emails ARRAY<STRING>,
company STRUCT<_dummy_:BIGINT,id:BIGINT,name:STRING>,
company_id BIGINT,
created_at STRING,
created_at_ts BIGINT,
custom_fields STRUCT<cf__call_reminder:STRING,cf__components:STRING,cf__isvcs:BOOLEAN,cf__l1_time_actual:STRING,cf__l1_time_allowed:STRING,cf__l1_violated:STRING,cf__l2_time_actual:STRING,cf__l2_time_allowed:STRING,cf__l2_violated:STRING,cf__l3_time_actual:STRING,cf__l3_time_allowed:STRING,cf__l3_violated:STRING,cf__l4_time_actual:STRING,cf__l4_time_allowed:STRING,cf__l4_violated:STRING,cf__merge:STRING,cf__segment:STRING,cf__ticket_cx_report:BOOLEAN,cf_agent_l1:STRING,cf_ai_sentiment:STRING,cf_chng_trnh_hng_ng:STRING,cf_company:STRING,cf_component:STRING,cf_csat_rating:BIGINT,cf_customer_entry_channel:STRING,cf_customer_respond_date:STRING,cf_exception:STRING,cf_hide_field:STRING,cf_hiu_qu_trao_i:STRING,cf_imported_ticket_date:STRING,cf_imported_ticket_due_date:STRING,cf_imported_ticket_id:STRING,cf_imported_ticket_link:STRING,cf_incident_root_cause:STRING,cf_issues_type:STRING,cf_l1:BOOLEAN,cf_l2:BOOLEAN,cf_l3:BOOLEAN,cf_l4:BOOLEAN,cf_legacy_id:STRING,cf_link_kb:STRING,cf_nh_gi_mc_x_l:STRING,cf_note:STRING,cf_number_of_due_date_changes:BIGINT,cf_old_due_date:STRING,cf_onedaybeforedue:BOOLEAN,cf_onehourbeforedue:BOOLEAN,cf_product_category:STRING,cf_reason:STRING,cf_related_ticket:STRING,cf_reminder_update:BOOLEAN,cf_rt_notification:BOOLEAN,cf_rt_overdue:STRING,cf_rt_time:STRING,cf_sentiment:STRING,cf_severity:STRING,cf_spam_type:STRING,cf_subtype:STRING,cf_thirdfourtime:BOOLEAN,cf_timer_history:STRING,cf_ttr_overdue:STRING,cf_ttr_time:STRING,cf_twothirdtime:BOOLEAN,cf_urgency:STRING>,
deleted BOOLEAN,
description STRING,
description_text STRING,
due_by STRING,
due_by_ts BIGINT,
email_config_id BIGINT,
form_id BIGINT,
fr_due_by STRING,
fr_due_by_ts BIGINT,
fr_escalated BOOLEAN,
fwd_emails ARRAY<STRING>,
group_id BIGINT,
id BIGINT,
is_escalated BOOLEAN,
nr_due_by STRING,
nr_due_by_ts BIGINT,
nr_escalated BOOLEAN,
priority BIGINT,
product_id BIGINT,
reply_cc_emails ARRAY<STRING>,
requester STRUCT<email:STRING,id:BIGINT,mobile:STRING,name:STRING,phone:STRING>,
requester_id BIGINT,
responder_id BIGINT,
source BIGINT,
spam BOOLEAN,
stats STRUCT<agent_responded_at:STRING,closed_at:STRING,first_responded_at:STRING,pending_since:STRING,reopened_at:STRING,requester_responded_at:STRING,resolved_at:STRING,status_updated_at:STRING>,
status BIGINT,
subject STRING,
support_email STRING,
tags ARRAY<STRING>,
ticket_bcc_emails ARRAY<STRING>,
ticket_cc_emails ARRAY<STRING>,
to_emails ARRAY<STRING>,
type STRING,
updated_at STRING,
updated_at_ts BIGINT,
  crawled_at_ts BIGINT
)
USING PARQUET
LOCATION 's3a://vcs-raw/cx-cso-raw/fact_cso_tickets'
;