
CREATE SCHEMA IF NOT EXISTS hive.personal_raw;

CREATE TABLE IF NOT EXISTS hive.personal_raw.objective (
  c_assignee VARCHAR,
  c_associated_contributions VARCHAR,
  c_associated_departments_portfolio VARCHAR,
  c_calculate_progress VARCHAR,
  c_department VARCHAR,
  c_description VARCHAR,
  c_n1_result_response VARCHAR,
  c_normalized_score DOUBLE,
  c_objective_progress_m VARCHAR,
  c_objective_progress_n VARCHAR,
  c_objective_type VARCHAR,
  c_planned_revenue_m_rollup DOUBLE,
  c_planned_revenue_n_rollup DOUBLE,
  c_record_type VARCHAR,
  c_reporter VARCHAR,
  c_tot_plan_cont_rollup_m DOUBLE,
  c_tot_plan_cont_rollup_n DOUBLE,
  c_total_planned_objectives_m DOUBLE,
  c_total_planned_objectives_n DOUBLE,
  c_total_planned_target_m DOUBLE,
  c_total_planned_target_n DOUBLE,
  c_total_weight_assignments DOUBLE,
  c_total_weight_percentage DOUBLE,
  c_trigger_wfr DOUBLE,
  c_trigger_wr BOOLEAN,
  attachments_count DOUBLE,
  emails_count DOUBLE,
  notes_count DOUBLE,
  sub_objectives_count DOUBLE,
  percent_of_plan DOUBLE,
  actual_percent DOUBLE,
  entity_owner VARCHAR,
  associated_item VARCHAR,
  created_by VARCHAR,
  created_on DATE,
  currency_exchange_date DATE,
  description VARCHAR,
  end_date DATE,
  external_id VARCHAR,
  sysid VARCHAR,
  entity_type VARCHAR,
  last_updated_by VARCHAR,
  last_updated_on DATE,
  name VARCHAR,
  parent_objective VARCHAR,
  planned_percent DOUBLE,
  start_date DATE,
  state VARCHAR,
  status VARCHAR,
  last_updated_by_system_on DATE,
  weight DOUBLE,
   _raw_payload VARCHAR,
   _batch_id VARCHAR,
   _ingest_timestamp TIMESTAMP(6),
  ingest_date DATE
)
WITH (
    format = 'PARQUET',
    external_location = '/opt/datasets/crawlers/vcs/clarizen/data/personal_raw/objective'
);


CREATE SCHEMA IF NOT EXISTS hive.global_clean;

CREATE TABLE IF NOT EXISTS hive.global_clean.objective (
  c_assignee VARCHAR,
  c_associated_contributions VARCHAR,
  c_associated_departments_portfolio VARCHAR,
  c_calculate_progress VARCHAR,
  c_department VARCHAR,
  c_description VARCHAR,
  c_n1_result_response VARCHAR,
  c_normalized_score DOUBLE,
  c_objective_progress_m VARCHAR,
  c_objective_progress_n VARCHAR,
  c_objective_type VARCHAR,
  c_planned_revenue_m_rollup DOUBLE,
  c_planned_revenue_n_rollup DOUBLE,
  c_record_type VARCHAR,
  c_reporter VARCHAR,
  c_tot_plan_cont_rollup_m DOUBLE,
  c_tot_plan_cont_rollup_n DOUBLE,
  c_total_planned_objectives_m DOUBLE,
  c_total_planned_objectives_n DOUBLE,
  c_total_planned_target_m DOUBLE,
  c_total_planned_target_n DOUBLE,
  c_total_weight_assignments DOUBLE,
  c_total_weight_percentage DOUBLE,
  c_trigger_wfr DOUBLE,
  c_trigger_wr BOOLEAN,
  attachments_count DOUBLE,
  emails_count DOUBLE,
  notes_count DOUBLE,
  sub_objectives_count DOUBLE,
  percent_of_plan DOUBLE,
  actual_percent DOUBLE,
  entity_owner VARCHAR,
  associated_item VARCHAR,
  created_by VARCHAR,
  created_on DATE,
  currency_exchange_date DATE,
  description VARCHAR,
  end_date DATE,
  external_id VARCHAR,
  sysid VARCHAR,
  entity_type VARCHAR,
  last_updated_by VARCHAR,
  last_updated_on DATE,
  name VARCHAR,
  parent_objective VARCHAR,
  planned_percent DOUBLE,
  start_date DATE,
  state VARCHAR,
  status VARCHAR,
  last_updated_by_system_on DATE,
  weight DOUBLE,
   _batch_id VARCHAR,
   _ingest_timestamp TIMESTAMP(6),
  ingest_date DATE
)
WITH (
    format = 'PARQUET',
    external_location = '/opt/datasets/crawlers/vcs/clarizen/data/global_clean/objective'
);
